"""do localization in study word

Revision ID: 1eee104f62ef
Revises: f90fe4b92655
Create Date: 2026-01-05 02:45:31.717037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eee104f62ef'
down_revision: Union[str, Sequence[str], None] = 'f90fe4b92655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_words', sa.Column('word_ru', sa.String(length=100), nullable=False))
    op.add_column('study_words', sa.Column('word_kk', sa.String(length=100), nullable=False))
    op.add_column('study_words', sa.Column('word_en', sa.String(length=100), nullable=False))
    op.add_column('study_words', sa.Column('usage_context_kk', sa.String(), nullable=False))
    op.add_column('study_words', sa.Column('usage_context_en', sa.String(), nullable=False))
    op.add_column('study_words', sa.Column('usage_context_ru', sa.String(), nullable=False))
    op.drop_column('study_words', 'translation')
    op.drop_column('study_words', 'word')
    op.drop_column('study_words', 'usage_context')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('study_words', sa.Column('usage_context', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('study_words', sa.Column('word', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('study_words', sa.Column('translation', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('study_words', 'usage_context_ru')
    op.drop_column('study_words', 'usage_context_en')
    op.drop_column('study_words', 'usage_context_kk')
    op.drop_column('study_words', 'word_en')
    op.drop_column('study_words', 'word_kk')
    op.drop_column('study_words', 'word_ru')
    # ### end Alembic commands ###
