"""remove some fields

Revision ID: 2b69d882cf98
Revises: 1eee104f62ef
Create Date: 2026-01-05 19:22:26.291103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b69d882cf98'
down_revision: Union[str, Sequence[str], None] = '1eee104f62ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_answers', 'user_response')
    op.drop_column('user_answers', 'is_correct')
    op.drop_column('user_answers', 'ai_feedback')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('ai_feedback', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('user_answers', sa.Column('is_correct', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('user_answers', sa.Column('user_response', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
