"""create new table training

Revision ID: 2e9e473474e3
Revises: a6a5f1cbaec9
Create Date: 2026-01-06 01:52:00.626008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9e473474e3'
down_revision: Union[str, Sequence[str], None] = 'a6a5f1cbaec9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trainings',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('accuracy', sa.FLOAT(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('trainings')
    # ### end Alembic commands ###
