"""add accuracy field in user answer

Revision ID: 86b52821170f
Revises: 2b69d882cf98
Create Date: 2026-01-05 19:39:09.408165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86b52821170f'
down_revision: Union[str, Sequence[str], None] = '2b69d882cf98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('accuracy', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_answers', 'accuracy')
    # ### end Alembic commands ###
