"""replaces question id to edge id

Revision ID: a6a5f1cbaec9
Revises: 86b52821170f
Create Date: 2026-01-05 20:15:18.585269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6a5f1cbaec9'
down_revision: Union[str, Sequence[str], None] = '86b52821170f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('roadmap_edge_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('user_answers_question_id_fkey'), 'user_answers', type_='foreignkey')
    op.create_foreign_key(None, 'user_answers', 'roadmap_edges', ['roadmap_edge_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_answers', 'question_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_answers', sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'user_answers', type_='foreignkey')
    op.create_foreign_key(op.f('user_answers_question_id_fkey'), 'user_answers', 'questions', ['question_id'], ['id'], ondelete='CASCADE')
    op.drop_column('user_answers', 'roadmap_edge_id')
    # ### end Alembic commands ###
