"""add new field level

Revision ID: afea6ff482c5
Revises: df1074961f5f
Create Date: 2026-01-04 23:20:25.719436

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision: str = 'afea6ff482c5'
down_revision: Union[str, Sequence[str], None] = 'df1074961f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
            DO $$
            BEGIN
                IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'englishlevel') THEN
                    CREATE TYPE englishlevel AS ENUM (
                        'BEGINNER', 
                        'ELEMENTARY', 
                        'INTERMEDIATE', 
                        'UPPER_INTERMEDIATE', 
                        'ADVANCED'
                    );
                END IF;
            END $$;
        """)
    op.add_column('roadmap_edges', sa.Column('level',
                                             ENUM('BEGINNER', 'ELEMENTARY', 'INTERMEDIATE', 'UPPER_INTERMEDIATE',
                                                  'ADVANCED', name='englishlevel', create_type=True), nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmap_edges', 'level')
    # ### end Alembic commands ###
