"""init tables

Revision ID: df1074961f5f
Revises: 
Create Date: 2026-01-04 22:57:36.344969

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'df1074961f5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roadmap_edges',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('x', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(), nullable=False),
                    sa.CheckConstraint('x >= -1 AND x <= 1', name='ck_x_range'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('users',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(), nullable=False),
                    sa.Column('fullname', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('email')
                    )
    op.create_table('profiles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('age', sa.Integer(), nullable=True),
                    sa.Column('system_language', sa.String(), nullable=True),
                    sa.Column('learning_goal', sa.String(), nullable=True),
                    sa.Column('current_english_level', sa.String(), nullable=True),
                    sa.Column('interests', sa.ARRAY(sa.String()), nullable=False),
                    sa.Column('daily_training_spend', sa.Integer(), nullable=False, comment='Минут өлшем бірлігі'),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('questions',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('edge_id', sa.Integer(), nullable=False),
                    sa.Column('type', sa.String(), nullable=False),
                    sa.Column('content', sa.JSON(), nullable=False),
                    sa.Column('difficulty', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['edge_id'], ['roadmap_edges.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('study_words',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('word', sa.String(length=100), nullable=False),
                    sa.Column('usage_context', sa.String(), nullable=False),
                    sa.Column('translation', sa.String(), nullable=False),
                    sa.Column('edge_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['edge_id'], ['roadmap_edges.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user_answers',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('question_id', sa.Integer(), nullable=False),
                    sa.Column('user_response', sa.String(), nullable=False),
                    sa.Column('is_correct', sa.Boolean(), nullable=False),
                    sa.Column('ai_feedback', sa.String(), nullable=True),
                    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
                    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answers')
    op.drop_table('study_words')
    op.drop_table('questions')
    op.drop_table('profiles')
    op.drop_table('users')
    op.drop_table('roadmap_edges')
    # ### end Alembic commands ###
