"""add new description field in edge

Revision ID: e9bef48957cd
Revises: afea6ff482c5
Create Date: 2026-01-05 00:41:28.429513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9bef48957cd'
down_revision: Union[str, Sequence[str], None] = 'afea6ff482c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roadmap_edges', sa.Column('description_of_edge', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roadmap_edges', 'description_of_edge')
    # ### end Alembic commands ###
